# -*- coding: utf-8 -*-
"""TinkerkitKinematic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQ-k6fU9JPXlGYXvFxP8pqUaBMhnErtw
"""

from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import cv2
import matplotlib.pyplot as plt 
import math

theta1=90
theta2=90
theta3=90
theta4=90
theta5=0


theta1=(theta1)*math.pi/180;
theta2=-(theta2-90)*math.pi/180;
theta3=-(theta3-90)*math.pi/180;
theta4=-(theta4-90)*math.pi/180;
theta5=-(theta5-90)*math.pi/180;
d_1=6.5; 
d_2=12.5;
d_3=12.5;
d_4=19; 
d_5=0;

R1=[[np.cos(theta1), -np.sin(theta1), 0,    0],
    [np.sin(theta1),  np.cos(theta1), 0,    0],
    [             0,                  0, 1, 0],
    [             0,                  0, 0, 1]]


T1=[[1,0,0,  0],
    [0,1,0,  0],
    [0,0,1,d_1],
    [0,0,0,  1]]

A0_1=np.dot(R1,T1)
       
R2=[[np.cos(theta2), 0,np.sin(theta2),  0],
   [              0, 1,             0,  0],
   [-np.sin(theta2), 0,np.cos(theta2),  0],
   [              0, 0,             0,  1]]
          

T2=[[1,0,0,  0],
    [0,1,0,  0],
    [0,0,1,d_2],
    [0,0,0,  1]]

A1_2=np.dot(R2,T2)

R3=[[np.cos(theta3), 0,np.sin(theta3),  0],
   [              0, 1,             0,  0],
   [-np.sin(theta3), 0,np.cos(theta3),  0],
   [              0, 0,             0,  1]]
         
T3=[[1,0,0,  0],
    [0,1,0,  0],
    [0,0,1,d_3],
    [0,0,0,  1]]

A2_3=np.dot(R3,T3)

R4=[[np.cos(theta4), 0,np.sin(theta4),  0],
   [              0, 1,             0,  0],
   [-np.sin(theta4), 0,np.cos(theta4),  0],
   [              0, 0,             0,  1]]

T4=[[1,0,0,  0],
    [0,1,0,  0],
    [0,0,1,d_4],
    [0,0,0,  1]] 

A3_4=np.dot(R4,T4)

R5=[[np.cos(theta5), -np.sin(theta5), 0,    0],
    [np.sin(theta5),  np.cos(theta5), 0,    0],
    [             0,                  0, 1, 0],
    [             0,                  0, 0, 1]]

T5=[[1,0,0,  0],
    [0,1,0,  0],
    [0,0,1,d_5],
    [0,0,0,  1]]

A4_5=np.dot(R5,T5)

A0_2=np.dot(A0_1,A1_2)
A0_3=np.dot(A0_2,A2_3)
A0_4=np.dot(A0_3,A3_4)
A0_5=np.dot(A0_4,A4_5);

P1=A0_1[:,3]
P2=A0_2[:,3]
P3=A0_3[:,3]
P4=A0_4[:,3]
P5=A0_5[:,3]

X=(0,P1[0],P2[0],P3[0],P4[0],P5[0])
Y=(0,P1[1],P2[1],P3[1],P4[1],P5[1])
Z=(0,P1[2],P2[2],P3[2],P4[2],P5[2])

x=(0,P1[0],P2[0],P3[0],P4[0],P5[0])
y=(0,P1[1],P2[1],P3[1],P4[1],P5[1])
z=(0,P1[2],P2[2],P3[2],P4[2],P5[2])

ax = plt.gca(projection="3d")
ax.scatter(x,y,z, c='b',s=100)
ax.plot(x,y,z, color='r')

plt.show()
x=A0_4[0,3]
y=A0_4[1,3]
z=A0_4[2,3]

print(x)
print(y)
print(z)